apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capz-serving-cert
  namespace: capz-system
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-giantswarm
  secretName: capz-webhook-service-cert
