apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capz-serving-cert
  namespace: capz-system
spec:
  dnsNames:
  - capz-webhook-service.{{ .Release.Namespace }}.svc
  - capz-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-giantswarm
  secretName: capz-webhook-service-cert
