---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: common-labels
labels:
  application.giantswarm.io/branch: '{{ .Values.project.branch }}'
  application.giantswarm.io/commit: '{{ .Values.project.commit }}'
  app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  helm.sh/chart: cluster-api-provider-azure
  app.kubernetes.io/name: cluster-api-provider-azure
  app.kubernetes.io/instance: '{{ .Release.Name }}'
  application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team" }}'
fieldSpecs:
  - path: metadata/labels
    create: true
