---
# The following patch adds clusterctl labels required to do the move operation
# correctly.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "ignored" # not important, we are applying this patch to all CAPA CRDs
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
    clusterctl.cluster.x-k8s.io: ""
