# We are not using leader election in our current release, since we are
# only deploying a single webhook pod.
---
$patch: delete
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: capz-selfsigned-issuer
  namespace: capz-system
