# We are not using leader election in our current release, since we are
# only deploying a single webhook pod.
---
$patch: delete
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: capz-nmi
  namespace: capz-system

---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capz-aad-pod-id-nmi-role
  namespace: capz-system

---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capz-aad-pod-id-nmi-binding
  namespace: capz-system
