# We are using our own AAD Pod Identity APP
# Only delete the NMI daemonset, we need the RBAC
---
$patch: delete
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: capz-nmi
  namespace: capz-system
