apiVersion: apps/v1
kind: Deployment
metadata:
  name: capz-controller-manager
  namespace: capz-system
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - --metrics-bind-addr=0.0.0.0:8080
            - --feature-gates=MachinePool=true,AKS=false
            - --watch-filter="{{- include "deployment.args.watchfiltervalue" . -}}"
            - --v=0
