---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azureserviceoperator-controller-manager
  namespace: capz-system
spec:
  template:
    spec:
      containers:
        - name: kube-rbac-proxy
          $patch: delete
