apiVersion: apps/v1
kind: Deployment
metadata:
  name: capz-controller-manager
  namespace: capz-system
spec:
  template:
    spec:
      containers:
        - name: manager
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
