apiVersion: apps/v1
kind: Deployment
metadata:
  name: capz-controller-manager
  namespace: capz-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  key: "azure.azureoperator.subscriptionid"
                  name: credential-default
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: "azure.azureoperator.tenantid"
                  name: credential-default
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: "azure.azureoperator.clientid"
                  name: credential-default
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: "azure.azureoperator.clientsecret"
                  name: credential-default
