namespace: '{{ .Release.Namespace }}'

resources:
  - input/infrastructure-components.yaml
  - ssh-sso-public-key-secret.yaml
  - secret-bootstrap-credentials.yaml

transformers:
  - common-labels.yaml
  - webhook-prefix.yaml

images:
  - name: registry.k8s.io/cluster-api-azure/cluster-api-azure-controller
    newName: "{{.Values.image.registry}}/{{.Values.image.name}}"
    newTag: "{{.Values.image.tag}}"

patchesStrategicMerge:
  - deployment-args.yaml
  - deployment-affinity.yaml
  - deployment-environment.yaml
  - deployment-metrics-port.yaml
  - deployment-securitycontext.yaml
  - deployment-toleration.yaml
  - deployment-aso-securitycontext.yaml
  - webhook-certificate.yaml
  - service-add-metrics-port.yaml
  - certificate.yaml
  - delete-selfsigned-cert-issuer.yaml
  - delete-ns.yaml
  - delete-nmi.yaml

patches:
- path: delete_aadpodidentity_crds.yaml
  target:
    kind: CustomResourceDefinition
    annotationSelector: api-approved.kubernetes.io=unapproved
- path: crd_cainjection.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- path: crd_webhook.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- path: crd_kubebuilder_version.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- path: crd_clusterctl_labels.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- target:
    kind: ValidatingWebhookConfiguration
  path: validating-webhook-watchfilter.yaml
- target:
    kind: MutatingWebhookConfiguration
  path: mutating-webhook-watchfilter.yaml
- target:
    kind: Secret
    name: capz-manager-bootstrap-credentials
  patch: |-
    - op: replace
      path: /metadata/name
      value: credential-default
- target:
    kind: DaemonSet
    name: capz-nmi
  path: daemonset-nmi-args.yaml
- target:
    kind: CustomResourceDefinition
    name: (azuremanagedmachinepools|azuremanagedcontrolplanes|azuremanagedclusters).infrastructure.cluster.x-k8s.io
  patch: |-
    - op: remove
      path: /metadata/creationTimestamp
