apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cluster API Provider Azure components
- bases/infrastructure-components.yaml
# Secrets
- bases/secrets/cluster-api-provider-azure-ssh-sso-pub-key.yaml
- secret-bootstrap-credentials.yaml

namespace: "{{ .Release.Namespace }}"

transformers:
  - common-labels.yaml
  - webhook-prefix.yaml

images:
  - name: registry.k8s.io/cluster-api-azure/cluster-api-azure-controller
    newName: "{{.Values.image.registry}}/{{.Values.image.name}}"
    newTag: "{{.Values.image.tag}}"
  - name: mcr.microsoft.com/k8s/azureserviceoperator:v2.4.0
    newName: "{{.Values.aso.image.registry}}/{{.Values.aso.image.name}}"

patchesStrategicMerge:
  - deployment-capz-args.yaml
  - deployment-affinity.yaml
  - deployment-environment.yaml
  - deployment-metrics-port.yaml
  - deployment-securitycontext.yaml
  - deployment-toleration.yaml
  - deployment-aso-securitycontext.yaml
  - deployment-aso-volume.yaml
  - webhook-certificate.yaml
  - webhook-certificate-aso.yaml
  - service-add-metrics-port.yaml
  - certificate.yaml
  - certificate-serviceoperator.yaml
  - delete-selfsigned-cert-issuer.yaml
  - delete-ns.yaml
  - delete-nmi.yaml
  - secret-aso-controller-settings.yaml

patches:
- path: deployment-aso-remove-kube-proxy.yaml
- path: delete_aadpodidentity_crds.yaml
  target:
    kind: CustomResourceDefinition
    annotationSelector: api-approved.kubernetes.io=unapproved
- path: crd_cainjection.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- path: aso_crd_cainjection.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: app.kubernetes.io/name=azure-service-operator
- path: crd_webhook.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- path: crd_clusterctl_labels.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- target:
    kind: ValidatingWebhookConfiguration
  path: validating-webhook-watchfilter.yaml
- target:
    kind: MutatingWebhookConfiguration
  path: mutating-webhook-watchfilter.yaml
- target:
    kind: Secret
    name: capz-manager-bootstrap-credentials
  patch: |-
    - op: replace
      path: /metadata/name
      value: credential-default
- target:
    kind: DaemonSet
    name: capz-nmi
  path: daemonset-nmi-args.yaml
- target:
    kind: Service
    labelSelector: app.kubernetes.io/name=azure-service-operator
  patch: |-
    - op: replace
      path: /spec/selector
      value:
        app.kubernetes.io/name: azure-service-operator
- target:
    kind: Service
    name: azureserviceoperator-proxy-service
  patch: |-
    - op: replace
      path: /spec/selector
      value:
        app.kubernetes.io/name: azure-service-operator
- target:
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/creationTimestamp
      value: null
    - op: remove
      path: /metadata/creationTimestamp
