namespace: '{{ .Release.Namespace }}'

resources:
  - input/infrastructure-components.yaml
  - ssh-sso-public-key-secret.yaml

transformers:
  - common-labels.yaml
  - webhook-prefix.yaml

images:
  - name: registry.k8s.io/cluster-api-azure/cluster-api-azure-controller
    newName: "{{.Values.image.registry}}/{{.Values.image.name}}"
    newTag: "{{.Values.image.tag}}"

patchesStrategicMerge:
  - deployment-args.yaml
  - deployment-environment.yaml
  - deployment-metrics-port.yaml
  - webhook-watchfilter.yaml
  - webhook-certificate.yaml
  - service-prometheus-annotations.yaml
  - service-add-metrics-port.yaml
  - secret-bootstrap-credentials.yaml
  - certificate.yaml
  - delete-nmi.yaml
  - delete-selfsigned-cert-issuer.yaml
  - delete-ns.yaml

patches:
- path: crd_cainjection.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- path: crd_webhook.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- path: delete_aadpodidentity_crds.yaml
  target:
    kind: CustomResourceDefinition
    annotationSelector: api-approved.kubernetes.io=unapproved
- path: crd_kubebuilder_version.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- target:
    kind: Secret
    name: capz-manager-bootstrap-credentials
  patch: |-
    - op: replace
      path: /metadata/name
      value: credential-default
