apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cluster API Provider Azure components
- bases/infrastructure-components.yaml
# Secrets
- bases/secrets/cluster-api-provider-azure-ssh-sso-pub-key.yaml
- bases/secrets/credential-default.yaml

namespace: "{{ .Release.Namespace }}"

labels:
# Common labels
- pairs:
    helm.sh/chart: cluster-api-provider-azure
    app.kubernetes.io/name: cluster-api-provider-azure
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    application.giantswarm.io/branch: "{{ .Values.project.branch }}"
    application.giantswarm.io/commit: "{{ .Values.project.commit }}"
    application.giantswarm.io/team: "{{ index .Chart.Annotations \"application.giantswarm.io/team\" }}"

images:
# Cluster API Provider Azure
- name: registry.k8s.io/cluster-api-azure/cluster-api-azure-controller
  newName: "{{ .Values.image.registry }}/{{ .Values.image.name }}"
  newTag: "{{ .Values.image.tag }}"
# Azure Service Operator
- name: mcr.microsoft.com/k8s/azureserviceoperator
  newName: "{{ .Values.aso.image.registry }}/{{ .Values.aso.image.name }}"

transformers:
# Mutating webhooks
- patches/mutatingwebhooks/zzz-prefix.yaml

patchesStrategicMerge:
  - delete-selfsigned-cert-issuer.yaml
  - delete-ns.yaml
  - delete-nmi.yaml
  - secret-aso-controller-settings.yaml

patches:
- path: deployment-aso-remove-kube-proxy.yaml
- path: delete_aadpodidentity_crds.yaml
  target:
    kind: CustomResourceDefinition
    annotationSelector: api-approved.kubernetes.io=unapproved
- path: crd_cainjection.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- path: aso_crd_cainjection.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: app.kubernetes.io/name=azure-service-operator
- path: crd_webhook.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- path: crd_clusterctl_labels.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=infrastructure-azure
- target:
    kind: ValidatingWebhookConfiguration
  path: validating-webhook-watchfilter.yaml
- target:
    kind: MutatingWebhookConfiguration
  path: mutating-webhook-watchfilter.yaml
- target:
    kind: DaemonSet
    name: capz-nmi
  path: daemonset-nmi-args.yaml
- target:
    kind: Service
    labelSelector: app.kubernetes.io/name=azure-service-operator
  patch: |-
    - op: replace
      path: /spec/selector
      value:
        app.kubernetes.io/name: azure-service-operator
- target:
    kind: Service
    name: azureserviceoperator-proxy-service
  patch: |-
    - op: replace
      path: /spec/selector
      value:
        app.kubernetes.io/name: azure-service-operator
- target:
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/creationTimestamp
      value: null
    - op: remove
      path: /metadata/creationTimestamp

# Certificates
- path: patches/certificates/azureserviceoperator-serving-cert.yaml
- path: patches/certificates/capz-serving-cert.yaml

# Deployments
- path: patches/deployments/azureserviceoperator-controller-manager.yaml
- path: patches/deployments/capz-controller-manager.yaml

# Services
- path: patches/services/capz-webhook-service.yaml

# Mutating webhooks
- path: patches/mutatingwebhooks/azureserviceoperator-mutating-webhook-configuration.yaml
- path: patches/mutatingwebhooks/capz-mutating-webhook-configuration.yaml

# Validating webhooks
- path: patches/validatingwebhooks/azureserviceoperator-validating-webhook-configuration.yaml
- path: patches/validatingwebhooks/capz-validating-webhook-configuration.yaml
