namespace: '{{ .Release.Namespace }}'
#namePrefix: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-'

#commonAnnotations:
#  meta.helm.sh/release-name: '{{ .Release.Name }}'
#  meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'

commonLabels:
  app.giantswarm.io/branch: '{{ .Values.project.branch }}'
  app.giantswarm.io/commit: '{{ .Values.project.commit }}'
  app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
  app.kubernetes.io/instance: '{{ .Release.Name }}'

images:
  - name: us.gcr.io/k8s-artifacts-prod/cluster-api-azure/cluster-api-azure-controller
    newName: "{{ .Values.registry.domain }}/{{ .Values.image.name }}"
    newTag: "{{ .Values.image.tag }}"

resources:
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/download/v1.0.1/infrastructure-components.yaml

patchesStrategicMerge:
  - deployment-args.yaml
  - delete-ns.yaml
  - webhook-watchfilter.yaml
  - service-prometheus-annotations.yaml
  - service-add-metrics-port.yaml

patches:
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: MutatingWebhookConfiguration
      name: capz-mutating-webhook-configuration
    path: mutating-webhook-prefix.yaml
