apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    giantswarm.io/monitoring: "true"
    giantswarm.io/monitoring-port: "8080"
  namespace: capz-system
  name: capz-webhook-service
