apiVersion: v1
kind: Secret
metadata:
  labels:
    role: "ssh-sso-public-key"
  name: cluster-api-provider-azure-ssh-sso-pub-key
  namespace: capz-system
data:
  value: "{{  .Values.workloadCluster.ssh.ssoPublicKey | b64enc }}"
