apiVersion: v1
kind: Secret
metadata:
  labels:
    role: "ssh-sso-public-key"
  name: cluster-api-provider-azure-ssh-sso-pub-key
  namespace: capz-system
data:
  value: "{{  .Values.Installation.V1.Guest.SSH.SSOPublicKey | b64enc }}"
