apiVersion: v1
kind: ServiceAccount
metadata:
  name: azureserviceoperator-default
  namespace: capz-system
  annotations:
    azure.workload.identity/client-id: "{{ .Values.azureWorkloadIdentity.clientId }}"
