apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api-provider-azure
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: cluster-api-provider-azure
  name: azureserviceoperator-serving-cert
  namespace: '{{ .Release.Namespace }}'
spec:
  dnsNames:
  - azureserviceoperator-webhook-service.capz-system.svc
  - azureserviceoperator-webhook-service.capz-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: azureserviceoperator-selfsigned-issuer
  secretName: webhook-server-cert
