apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api-provider-azure
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: infrastructure-azure
    helm.sh/chart: cluster-api-provider-azure
  name: capz-serving-cert
  namespace: '{{ .Release.Namespace }}'
spec:
  dnsNames:
  - capz-webhook-service.capz-system.svc
  - capz-webhook-service.capz-system.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-giantswarm
  secretName: capz-webhook-service-cert
