apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: infrastructure-azure
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_"
      | trunc 63 | trimSuffix "-" -}}'
  name: capz-serving-cert
  namespace: '{{ .Release.Namespace }}'
spec:
  dnsNames:
  - capz-webhook-service.capz-system.svc
  - capz-webhook-service.capz-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capz-selfsigned-issuer
  secretName: capz-webhook-service-cert
