apiVersion: v1
data:
  cloud-env: "AzurePublicCloud"
kind: ConfigMap
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
  name: capz-manager-bootstrap-cloud-env
  namespace: {{ include "resource.default.namespace" . }}
