apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aadpodidbinding: capz-controller-aadpodidentity-selector
    control-plane: capz-controller-manager
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: capz-controller-manager
      {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        aadpodidbinding: capz-controller-aadpodidentity-selector
        control-plane: capz-controller-manager
        {{- include "labels.common" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "resource.default.name" . }}
      containers:
      - args:
        - --metrics-bind-addr=0.0.0.0:8080
        - --feature-gates=MachinePool={{ .Values.featuregates.machinepool }},AKS={{ .Values.featuregates.aks }}
        - --watch-filter={{ include "resource.app.version" . }}
        env:
        - name: AZURE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: cloud-env
              name: "{{ include "resource.default.name" . }}-bootstrap-cloud-env"
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              key: "azure.azureoperator.subscriptionid"
              name: credential-default
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              key: "azure.azureoperator.tenantid"
              name: credential-default
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: "azure.azureoperator.clientid"
              name: credential-default
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: "azure.azureoperator.clientsecret"
              name: credential-default
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9440
          name: healthz
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
      terminationGracePeriodSeconds: 10
