{{ if eq .Values.provider.flavor "capi" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    application.giantswarm.io/branch: '{{ .Values.project.branch }}'
    application.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api-provider-azure
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: infrastructure-azure
    helm.sh/chart: cluster-api-provider-azure
    k8s-app: capz-aad-pod-id-nmi-binding
  name: capz-aad-pod-id-nmi-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capz-aad-pod-id-nmi-role
subjects:
- kind: ServiceAccount
  name: capz-manager
  namespace: '{{ .Release.Namespace }}'
{{ end }}
