apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    giantswarm.io/monitoring: "true"
    control-plane: capz-controller-manager
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-metrics
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "labels.selector" . | nindent 4 }}
    control-plane: capz-controller-manager
