apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    giantswarm.io/monitoring: "true"
    giantswarm.io/monitoring-port: "8080"
  labels:
    control-plane: capz-controller-manager
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-metrics
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    {{- include "labels.selector" . | nindent 4 }}
    control-plane: capz-controller-manager
