{{ if eq .Values.provider.flavor "capi" }}
apiVersion: v1
data:
  azure.azureoperator.clientid: '{{.Values.provider.clientId | b64enc}}'
  azure.azureoperator.clientsecret: '{{.Values.provider.clientSecret | b64enc}}'
  azure.azureoperator.subscriptionid: '{{.Values.provider.subscriptionId | b64enc}}'
  azure.azureoperator.tenantid: '{{.Values.provider.tenantId | b64enc}}'
  client-id: '{{.Values.provider.clientId | b64enc}}'
  client-secret: '{{.Values.provider.clientSecret | b64enc}}'
  subscription-id: '{{.Values.provider.subscriptionId | b64enc}}'
  tenant-id: '{{.Values.provider.tenantId | b64enc}}'
kind: Secret
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api-provider-azure
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team"
      }}'
    cluster.x-k8s.io/provider: infrastructure-azure
    helm.sh/chart: cluster-api-provider-azure
  name: credential-default
  namespace: '{{ .Release.Namespace }}'
{{ end }}
