apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api-provider-azure
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team"
      }}'
    cluster.x-k8s.io/provider: infrastructure-azure
    helm.sh/chart: cluster-api-provider-azure
  name: capz-manager
  namespace: '{{ .Release.Namespace }}'
