apiVersion: v1
data:
  value: '{{ .Values.workloadCluster.ssh.ssoPublicKey | quote }}'
kind: Secret
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api-provider-azure
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: cluster-api-provider-azure
    role: ssh-sso-public-key
  name: cluster-api-provider-azure-ssh-sso-pub-key
  namespace: '{{ .Release.Namespace }}'
