---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-cert
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: zzz-{{ include "resource.default.name" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha4-azurecluster
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.azurecluster.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azureclusters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremachine
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.azuremachine.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremachinetemplate
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.azuremachinetemplate.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachinetemplates
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremachinepool
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  name: default.azuremachinepool.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachinepools
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremanagedcontrolplane
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  name: default.azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremanagedcontrolplanes
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremanagedmachinepool
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  name: default.azuremanagedmachinepools.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremanagedmachinepools
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-cert
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-webhook
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-azurecluster
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.azurecluster.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azureclusters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremachine
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.azuremachine.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremachinetemplate
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.azuremachinetemplate.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachinetemplates
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremachinepool
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  name: validation.azuremachinepool.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachinepools
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremachinepoolmachine
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  name: azuremachinepoolmachine.kb.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachinepoolmachines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremanagedcontrolplane
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  name: validation.azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremanagedcontrolplanes
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-azuremanagedmachinepool
      port: {{ .Values.webhook.port }}
  failurePolicy: Fail
  name: validation.azuremanagedmachinepools.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremanagedmachinepools
