resources:
- infrastructure

patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider!=infrastructure-azure
  patch: |-
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1name
      value: azure-service-operator
