apiVersion: v1
kind: Secret
metadata:
  name: cluster-api-provider-azure-ssh-sso-pub-key
  namespace: capz-system
  labels:
    role: ssh-sso-public-key
data:
  value: "{{ .Values.workloadCluster.ssh.ssoPublicKey | b64enc }}"
