apiVersion: v1
kind: Secret
metadata:
  name: credential-default
  namespace: capz-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
data:
  subscription-id: "{{ .Values.provider.subscriptionId | b64enc }}"
  tenant-id: "{{ .Values.provider.tenantId | b64enc }}"
  client-id: "{{ .Values.provider.clientId | b64enc }}"
  client-secret: "{{ .Values.provider.clientSecret | b64enc }}"
  azure.azureoperator.subscriptionid: "{{ .Values.provider.subscriptionId | b64enc }}"
  azure.azureoperator.tenantid: "{{ .Values.provider.tenantId | b64enc }}"
  azure.azureoperator.clientid: "{{ .Values.provider.clientId | b64enc }}"
  azure.azureoperator.clientsecret: "{{ .Values.provider.clientSecret | b64enc }}"
