- op: replace
  path: /spec/versions/0/schema
  value:
    openAPIV3Schema:
      description: AzureManagedCluster is the Schema for the azuremanagedclusters API.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: AzureManagedClusterSpec defines the desired state of AzureManagedCluster.
          properties:
            controlPlaneEndpoint:
              description: |-
                ControlPlaneEndpoint represents the endpoint used to communicate with the control plane.
                Immutable, populated by the AKS API at create.
                Because this field is programmatically set by CAPZ after resource creation, we define it as +optional
                in the API schema to permit resource admission.
              properties:
                host:
                  description: host is the hostname on which the API server is serving.
                  maxLength: 512
                  type: string
                port:
                  description: port is the port on which the API server is serving.
                  format: int32
                  type: integer
              required:
                - host
                - port
              type: object
          type: object
        status:
          description: AzureManagedClusterStatus defines the observed state of AzureManagedCluster.
          properties:
            ready:
              description: Ready is true when the provider resource is ready.
              type: boolean
          type: object
      type: object
