- op: replace
  path: /spec/versions/0/schema
  value:
    openAPIV3Schema:
      description: AzureManagedClusterTemplate is the Schema for the AzureManagedClusterTemplates API.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: AzureManagedClusterTemplateSpec defines the desired state of AzureManagedClusterTemplate.
          properties:
            template:
              description: AzureManagedClusterTemplateResource describes the data needed to create an AzureManagedCluster from a template.
              properties:
                spec:
                  description: AzureManagedClusterTemplateResourceSpec specifies an Azure managed cluster template resource.
                  type: object
              required:
                - spec
              type: object
          required:
            - template
          type: object
      type: object
