apiVersion: apps/v1
kind: Deployment
metadata:
  name: azureserviceoperator-controller-manager
  namespace: capz-system
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  control-plane: controller-manager
              topologyKey: kubernetes.io/hostname
            weight: 10
      containers:
      - name: manager
        env:
        - name: ADDITIONAL_ASO_CRDS
          value: '{{ join ";" .Values.aso.additionalCRDs }}'
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      volumes:
      - name: cert
        secret:
          secretName: aso-webhook-service-cert
