apiVersion: apps/v1
kind: Deployment
metadata:
  name: capz-controller-manager
  namespace: capz-system
spec:
  template:
    spec:
      containers:
      - name: manager
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        args:
        - --leader-elect={{- if eq .Values.provider.flavor "capi" }}true{{ else }}false{{- end }}
        - --diagnostics-address=0.0.0.0:8080
        - --insecure-diagnostics=true
        - --feature-gates=MachinePool=true
        - --watch-filter={{- include "cluster-api-provider-azure.watchFilter" . }}
        - --v={{ .Values.controller.verbosity }}
        env:
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: credential-default
              key: azure.azureoperator.subscriptionid
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: credential-default
              key: azure.azureoperator.tenantid
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: credential-default
              key: azure.azureoperator.clientid
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: credential-default
              key: azure.azureoperator.clientsecret
        ports:
        - name: metrics
          protocol: TCP
          containerPort: 8080
        - $patch: delete
          name: metrics
          protocol: TCP
          containerPort: 8443
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            weight: 10
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      - key: node.cluster.x-k8s.io/uninitialized
        effect: NoSchedule
        operator: Exists
