apiVersion: apps/v1
kind: Deployment
metadata:
  name: capz-controller-manager
  namespace: capz-system
spec:
  template:
    spec:
      containers:
      - name: manager
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        args:
        - --leader-elect
        - --diagnostics-address=0.0.0.0:8080
        - --insecure-diagnostics=true
        - --feature-gates=MachinePool=true
        - --v={{ .Values.controller.verbosity }}
        ports:
        - name: metrics
          protocol: TCP
          containerPort: 8080
        - $patch: delete
          name: metrics
          protocol: TCP
          containerPort: 8443
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            weight: 10
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      - key: node.cluster.x-k8s.io/uninitialized
        effect: NoSchedule
        operator: Exists
