apiVersion: v1
kind: Service
metadata:
  name: capz-webhook-service
  namespace: capz-system
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  - name: webhook-server
    port: 443
    targetPort: webhook-server
