apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: capz-controller-manager
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api-provider-azure
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team" }}'
    cluster.x-k8s.io/provider: infrastructure-azure
    control-plane: capz-controller-manager
    helm.sh/chart: cluster-api-provider-azure
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-azure
