{{ if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" }}
{{ if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: capz-controller-manager
  namespace: '{{ .Release.Namespace }}'
  labels:
    application.giantswarm.io/branch: '{{ .Values.project.branch }}'
    application.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api-provider-azure
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team" }}'
    cluster.x-k8s.io/provider: infrastructure-azure
    control-plane: capz-controller-manager
    helm.sh/chart: cluster-api-provider-azure
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: manager
      controlledValues: RequestsAndLimits
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  capz-controller-manager
  updatePolicy:
    updateMode: Auto
{{ end }}
{{ end }}
