apiVersion: v1
kind: Secret
metadata:
  name: aso-controller-settings
  namespace: capz-system
type: Opaque
stringData:
  AZURE_AUTHORITY_HOST: ""
  AZURE_CLIENT_ID: "{{ .Values.provider.clientId }}"
  AZURE_RESOURCE_MANAGER_AUDIENCE: ""
  AZURE_RESOURCE_MANAGER_ENDPOINT: ""
  AZURE_SUBSCRIPTION_ID: "{{ .Values.provider.subscriptionId }}"
  AZURE_SYNC_PERIOD: ""
  AZURE_TENANT_ID: "{{ .Values.provider.tenantId }}"
