apiVersion: v1
kind: Secret
metadata:
  name: aso-controller-settings
  namespace: capz-system
stringData:
  AZURE_AUTHORITY_HOST: ""
  AZURE_RESOURCE_MANAGER_AUDIENCE: ""
  AZURE_RESOURCE_MANAGER_ENDPOINT: ""
  AZURE_SYNC_PERIOD: ""
