# This refers to a release in the Giant Swarm fork. The fork closely follows upstream releases unless hotfixes are
# needed. Please read https://github.com/giantswarm/cluster-api-provider-azure/blob/main/README.md on how to create a
# release. Please include the short commit SHA in the tag name, such as `v1.22.0-gs-123abcd`. After changing this
# tag, please run `make generate` to update CRDs and other manifests.

# Changes in this tag include upstream v1.22.x with additional:
#   * Giant Swarm fork modifications (https://github.com/giantswarm/cluster-api-provider-azure/pull/120)
#   * Add Private Link Support (https://github.com/giantswarm/cluster-api-provider-azure/pull/121)
#   * Fix RBAC for OwnerReferencesPermissionEnforcement feature (https://github.com/giantswarm/cluster-api-provider-azure/pull/122)

# -- Image settings.
image:
  # -- Image registry.
  registry: gsoci.azurecr.io
  # -- Image repository.
  name: giantswarm/cluster-api-azure-controller
  # -- Image tag.
  tag: v1.22.0-gs-0f7f47f68

# -- Azure Service Operator settings.
aso:
  # -- Image settings.
  image:
    # -- Image registry.
    registry: gsoci.azurecr.io
    # -- Image repository.
    name: giantswarm/azureserviceoperator

# -- Workload cluster settings.
workloadCluster:
  # -- SSH settings.
  ssh:
    # -- SSO public key.
    ssoPublicKey: ""

# -- Controller settings.
controller:
  # -- Log verbosity.
  verbosity: 0

# -- Vertical Pod Autoscaler settings.
verticalPodAutoscaler:
  # -- Whether to enable Vertical Pod Autoscaler or not.
  enabled: true

# -- Cilium Network Policy settings.
ciliumNetworkPolicy:
  # -- Whether to enable Cilium Network Policy or not.
  enabled: false

# -- Service Monitor settings.
serviceMonitor:
  # -- Whether to enable Service Monitor or not.
  enabled: true

# -- CRD install job settings.
crds:
  # -- Whether to install CRDs or not.
  install: true
