{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "crd-install.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "crd-install.labels" . | nindent 4 }}
  annotations:
    {{- include "crd-install.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-2"
spec:
  endpointSelector:
    matchLabels: {{- include "crd-install.labels" . | nindent 6 }}
  egress:
  - toEntities:
    - kube-apiserver
{{- end }}
