{{- if .Values.crds.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-api-provider-azure.crd-install.fullname" . }}
  labels:
    {{- include "cluster-api-provider-azure.crd-install.labels" . | nindent 4 }}
  annotations:
    {{- include "cluster-api-provider-azure.crd-install.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-api-provider-azure.crd-install.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-api-provider-azure.crd-install.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
