apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "capz.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "capz.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "capz.crdInstall" . | quote }}
    {{- include "capz.selectorLabels" . | nindent 4 }}
    role: {{ include "capz.CRDInstallSelector" . | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - patch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "capz.crdInstall" . }}
  verbs:
  - use
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - patch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "capz.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "capz.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "capz.crdInstall" . | quote }}
    {{- include "capz.selectorLabels" . | nindent 4 }}
    role: {{ include "capz.CRDInstallSelector" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "capz.crdInstall" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "capz.crdInstall" . }}
    namespace: {{ .Release.Namespace | quote }}
