apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crd-install.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "crd-install.labels" . | nindent 4 }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "crd-install.annotations" . | nindent 4 }}
