{{/*
We have to create individual configmaps for each CRD - they exceed the total
allowed length for a configmap if they are combined.
*/}}
{{ $currentScope := . }}
  {{- range $path, $_ := .Files.Glob "files/**.yaml" }}
    {{- with $currentScope }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crd-install.name" . }}-{{ include "capz.CRDInstallConfigmapNameGenerate" $path }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "crd-install.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "crd-install.name" . | quote }}
    {{- include "capz.selectorLabels" . | nindent 4 }}
    role: {{ include "capz.CRDInstallSelector" . | quote }}
data:
  content: |
{{ tpl ($.Files.Get $path) . | indent 4 }}
    {{- end }}
  {{- end }}
