apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api-provider-azure.crd-install.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "cluster-api-provider-azure.crd-install.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api-provider-azure.crd-install.fullname" . | quote }}
    {{- include "cluster-api-provider-azure.crd-install.selectorLabels" . | nindent 4 }}
