apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-api-provider-azure.crd-install.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "cluster-api-provider-azure.crd-install.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api-provider-azure.crd-install.fullname" . | quote }}
    {{- include "cluster-api-provider-azure.crd-install.selectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-api-provider-azure.crd-install.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster-api-provider-azure.crd-install.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
