apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ignored
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/azureserviceoperator-serving-cert"
