apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ignored
  labels:
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/move: ""
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/capz-serving-cert"
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          name: capz-webhook-service
          namespace: "{{ .Release.Namespace }}"
          port: 443
          path: /convert
