apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-api-provider-azure.crd-install.fullname" . }}
  labels:
    {{- include "cluster-api-provider-azure.crd-install.labels" . | nindent 4 }}
  annotations:
    {{- include "cluster-api-provider-azure.crd-install.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-2"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - list
  - get
  - patch
  - delete
