# We run azure-service-operator with --crd-management=auto
# This RBAC exists in original ASO manifests but it is being remove by CAPZ.
# This will be part of CAPZ manifests in 1.14.0 and newer versions.
# See https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4547/files
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azureserviceoperator-crd-manager
  labels:
    {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - list
  - watch
  - get
  - update
  - patch
