apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: azureserviceoperator-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: azure-service-operator
      control-plane: controller-manager
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
