{{- if .Values.ciliumNetworkPolicy.enabled -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: azureserviceoperator-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: azure-service-operator
      control-plane: controller-manager
  ingress:
  - fromEntities:
    - cluster
    - kube-apiserver
  egress:
  - toEntities:
    - cluster
    - kube-apiserver
{{- end }}
