apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: capz-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-azure
      control-plane: capz-controller-manager
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
