{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: capz-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-azure
      control-plane: capz-controller-manager
  endpoints:
  - port: metrics
{{- end }}
