resources:
  - bases/azureasomanagedclusters.infrastructure.cluster.x-k8s.io.yaml
  - bases/azureasomanagedclustertemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/azureasomanagedcontrolplanes.infrastructure.cluster.x-k8s.io.yaml
  - bases/azureasomanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/azureasomanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
  - bases/azureasomanagedmachinepooltemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/azureclusteridentities.infrastructure.cluster.x-k8s.io.yaml
  - bases/azureclusters.infrastructure.cluster.x-k8s.io.yaml
  - bases/azureclustertemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/azuremachinepoolmachines.infrastructure.cluster.x-k8s.io.yaml
  - bases/azuremachinepools.infrastructure.cluster.x-k8s.io.yaml
  - bases/azuremachines.infrastructure.cluster.x-k8s.io.yaml
  - bases/azuremachinetemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/azuremanagedclusters.infrastructure.cluster.x-k8s.io.yaml
  - bases/azuremanagedclustertemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io.yaml
  - bases/azuremanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/azuremanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
  - bases/azuremanagedmachinepooltemplates.infrastructure.cluster.x-k8s.io.yaml
  - bases/bastionhosts.network.azure.com.yaml
  - bases/extensions.kubernetesconfiguration.azure.com.yaml
  - bases/fleetsmembers.containerservice.azure.com.yaml
  - bases/managedclusters.containerservice.azure.com.yaml
  - bases/managedclustersagentpools.containerservice.azure.com.yaml
  - bases/natgateways.network.azure.com.yaml
  - bases/privateendpoints.network.azure.com.yaml
  - bases/resourcegroups.resources.azure.com.yaml
  - bases/virtualnetworks.network.azure.com.yaml
  - bases/virtualnetworkssubnets.network.azure.com.yaml
patches:
  - path: patches/versions/v1alpha1/azureasomanagedclusters.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedclusters.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1alpha1/azureasomanagedclustertemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedclustertemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1alpha1/azureasomanagedcontrolplanes.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedcontrolplanes.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1alpha1/azureasomanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1alpha1/azureasomanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedmachinepools.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1alpha1/azureasomanagedmachinepooltemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedmachinepooltemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azureclusteridentities.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureclusteridentities.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azureclusters.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureclusters.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azureclustertemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureclustertemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azuremachinepoolmachines.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachinepoolmachines.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azuremachinepools.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachinepools.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azuremachines.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachines.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azuremachinetemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachinetemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azuremanagedclusters.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedclusters.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azuremanagedclustertemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedclustertemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azuremanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azuremanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedmachinepools.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1beta1/azuremanagedmachinepooltemplates.infrastructure.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedmachinepooltemplates.infrastructure.cluster.x-k8s.io
  - path: patches/versions/v1api20220701/bastionhosts.network.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: bastionhosts.network.azure.com
  - path: patches/versions/v1api20220701storage/bastionhosts.network.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: bastionhosts.network.azure.com
  - path: patches/versions/v1api20230501/extensions.kubernetesconfiguration.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: extensions.kubernetesconfiguration.azure.com
  - path: patches/versions/v1api20230501storage/extensions.kubernetesconfiguration.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: extensions.kubernetesconfiguration.azure.com
  - path: patches/versions/v1api20230315preview/fleetsmembers.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: fleetsmembers.containerservice.azure.com
  - path: patches/versions/v1api20230315previewstorage/fleetsmembers.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: fleetsmembers.containerservice.azure.com
  - path: patches/versions/v1api20210501/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20210501storage/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20230201/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20230201storage/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20230202preview/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20230202previewstorage/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20231001/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20231001storage/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20231102preview/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20231102previewstorage/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20240402preview/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20240402previewstorage/managedclusters.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclusters.containerservice.azure.com
  - path: patches/versions/v1api20210501/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20210501storage/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20230201/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20230201storage/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20230202preview/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20230202previewstorage/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20231001/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20231001storage/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20231102preview/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20231102previewstorage/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20240402preview/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20240402previewstorage/managedclustersagentpools.containerservice.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: managedclustersagentpools.containerservice.azure.com
  - path: patches/versions/v1api20220701/natgateways.network.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: natgateways.network.azure.com
  - path: patches/versions/v1api20220701storage/natgateways.network.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: natgateways.network.azure.com
  - path: patches/versions/v1api20220701/privateendpoints.network.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: privateendpoints.network.azure.com
  - path: patches/versions/v1api20220701storage/privateendpoints.network.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: privateendpoints.network.azure.com
  - path: patches/versions/v1api20200601/resourcegroups.resources.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: resourcegroups.resources.azure.com
  - path: patches/versions/v1api20200601storage/resourcegroups.resources.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: resourcegroups.resources.azure.com
  - path: patches/versions/v1api20201101/virtualnetworks.network.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: virtualnetworks.network.azure.com
  - path: patches/versions/v1api20201101storage/virtualnetworks.network.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: virtualnetworks.network.azure.com
  - path: patches/versions/v1api20201101/virtualnetworkssubnets.network.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: virtualnetworkssubnets.network.azure.com
  - path: patches/versions/v1api20201101storage/virtualnetworkssubnets.network.azure.com.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: virtualnetworkssubnets.network.azure.com
