---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-cert
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha3-azurecluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.azurecluster.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - azureclusters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha3-azuremachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.azuremachine.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-exp-infrastructure-cluster-x-k8s-io-v1alpha3-azuremachinepool
  failurePolicy: Fail
  name: azuremachinepool.kb.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - exp.infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachinepools
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-exp-infrastructure-cluster-x-k8s-io-v1alpha3-azuremanagedcontrolplane
  failurePolicy: Fail
  name: azuremanagedcontrolplane.kb.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - exp.infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremanagedcontrolplanes
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-cert
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-webhook
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-azurecluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.azurecluster.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - azureclusters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-azuremachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.azuremachine.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-exp-infrastructure-cluster-x-k8s-io-v1alpha3-azuremachinepool
  failurePolicy: Fail
  name: azuremachinepool.kb.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - exp.infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachinepools
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-exp-infrastructure-cluster-x-k8s-io-v1alpha3-azuremanagedcontrolplane
  failurePolicy: Fail
  name: azuremanagedcontrolplane.kb.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - exp.infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremanagedcontrolplanes
