name: Templates
on: pull_request
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Generate templates
      run: make generate
    - name: Verify templates
      run: git diff --exit-code
